-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  firstName character varying,
  lastName character varying,
  role character varying NOT NULL DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'editor'::character varying, 'user'::character varying]::text[])),
  phone character varying,
  company character varying,
  profileImage character varying,
  bio text,
  isActive boolean DEFAULT true,
  createdAt timestamp without time zone DEFAULT now(),
  updatedAt timestamp without time zone DEFAULT now(),
  createdBy uuid,
  updatedBy uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_created_by_fkey FOREIGN KEY (createdBy) REFERENCES public.users(id),
  CONSTRAINT users_updated_by_fkey FOREIGN KEY (updatedBy) REFERENCES public.users(id)
);
CREATE TABLE public.form_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  formType character varying NOT NULL CHECK ("formType"::text = ANY (ARRAY['service-inquiry'::character varying, 'contact'::character varying, 'class-ecs-ecns'::character varying, 'icasa-type-approvals'::character varying, 'license-exemptions'::character varying, 'nrcs-loa'::character varying, 'radio-dealer'::character varying, 'ski-boat-vhf'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in-progress'::character varying, 'completed'::character varying, 'rejected'::character varying, 'archived'::character varying]::text[])),
  serviceId uuid,
  serviceName character varying,
  fullName character varying NOT NULL CHECK (length("fullName"::text) > 0),
  email character varying NOT NULL CHECK (email::text ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'::text),
  phone character varying,
  company character varying,
  industry character varying,
  details jsonb,
  internalNotes text,
  assignedTo uuid,
  createdAt timestamp without time zone DEFAULT now(),
  updatedAt timestamp without time zone DEFAULT now(),
  completedAt timestamp without time zone,
  CONSTRAINT form_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT form_submissions_assigned_to_fkey FOREIGN KEY (assignedTo) REFERENCES public.users(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  name text,
  phone text,
  service text,
  message text,
  submittedAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  href text NOT NULL,
  category text,
  description text,
  shortDescription text,
  icon text,
  orderIndex integer,
  content text,
  features ARRAY,
  requirements ARRAY,
  includes ARRAY,
  published boolean DEFAULT true,
  featured boolean DEFAULT false,
  createdAt timestamp with time zone DEFAULT now(),
  processingTime text,
  pricing numeric,
  image text,
  thumbnail text,
  seoTitle text,
  seoDescription text,
  seoKeywords text,
  pricingPlans jsonb,
  processSteps jsonb,
  successStory jsonb,
  updatedAt timestamp with time zone,
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  postUrl text NOT NULL,
  createdAt timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_posts (
  id character varying NOT NULL UNIQUE,
  title character varying NOT NULL CHECK (length(title::text) > 0),
  slug character varying NOT NULL UNIQUE CHECK (length(slug::text) > 0),
  excerpt text,
  content text NOT NULL CHECK (length(content) > 0),
  category character varying,
  tags character varying,
  readTime character varying,
  seoTitle character varying,
  seoDescription character varying,
  seoKeywords character varying,
  featuredImage character varying,
  thumbnail character varying,
  published boolean DEFAULT false,
  publishedAt timestamp without time zone,
  featured boolean DEFAULT false,
  authorId uuid,
  authorName character varying,
  viewsCount integer DEFAULT 0,
  createdAt timestamp without time zone DEFAULT now(),
  updatedAt timestamp without time zone DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (authorId) REFERENCES public.users(id)
);
